# Generated by Django 4.2.2 on 2023-07-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_create',
            new_name='data_create',
        ),
    ]
