# Generated by Django 4.2.2 on 2023-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_date_create_blog_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='опубликовано'),
        ),
    ]
