# Generated by Django 4.2.2 on 2023-07-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can publish post')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
